apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "httproute-prometheus-shim.fullname" . }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes","grpcroutes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "httproute-prometheus-shim.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "httproute-prometheus-shim.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "httproute-prometheus-shim.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
